#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:0
#SBATCH --job-name=SetupVG
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=0:45:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_setup_vg_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/FACT2023

source activate fact2023

# This script is used to download the Visual Genome dataset and extract the
# images and annotations.

# Download the Visual Genome dataset.
echo "Downloading the Visual Genome dataset..."
wget https://cs.stanford.edu/people/rak248/VG_100K_2/images.zip -P data/vg
wget https://cs.stanford.edu/people/rak248/VG_100K_2/images2.zip -P data/vg

# Extract the images.
echo "Extracting the images..."
unzip data/vg/images.zip -d data/vg
unzip data/vg/images2.zip -d data/vg

# Combine the images into one folder.
mv data/vg/VG_100K_2/* data/vg/VG_100K

# Remove the empty folders and zip files.
rm -r data/vg/VG_100K_2
rm data/vg/images.zip
rm data/vg/images2.zip

# Download the annotations.
echo "Downloading the annotations..."
wget http://visualgenome.org/static/data/dataset/objects.json.zip -P data/vg

# Extract the annotations.
unzip data/vg/objects.json.zip -d data/vg/vg_objects.json

# Remove the zip file.
rm data/vg/objects.json.zip

# Run the script to create the dataset.
echo "Creating the dataset..."
srun python -u ./data/vg/preprocess_vg.py
